security:

    enable_authenticator_manager: true

    providers:
        users:
            entity:
                class: App\Entity\Activity

    password_hashers:
        App\Entity\Activity:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/public/activities/login$
            stateless: true
            guard:
                authenticators:
                    - App\Security\EmailPasswordGuardAuthenticator
        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - App\Security\JWTGuardAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
