controllers_agregate:
    resource: ../../src/Aggregate/Infrastructure/Controller/
    type: annotation

controllers_activities:
    resource: ../../src/Activity/Infrastructure/Controller/
    type: annotation

controllers_items:
    resource: ../../src/Item/Infrastructure/Controller/
    type: annotation

controllers_sections:
    resource: ../../src/Section/Infrastructure/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
