version: '3.9'

services:
  database:
    container_name: 'database'
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD={DATABASE_PASSWORD}
      - POSTGRES_USER={DATABASE_USER}
      - POSTGRES_DB={DATABASE_NAME}
    ports:
    - '5432:5432'